# parser.py
from __future__ import annotations
import asyncio
import re
import time
from contextlib import asynccontextmanager
from pathlib import Path
from typing import List, Tuple, Optional
from urllib.parse import urlparse

from playwright.async_api import async_playwright

from config import PROFILES, UA, XIAOE_EXTRA_WAIT_MS, LOGIN_WAIT_MS, COOKIE_SOURCE
from utils import detect_platform_loose, cookie_file_for, normalize_xiaoe_url
import cookie_source

# 解析时顺带拿到的课程标题：page_url -> 标题（下载时用作文件名）
TITLES: dict = {}


def title_for(page_url: str) -> Optional[str]:
    return TITLES.get(page_url)


# ---------------------------------------------------------------- 媒体判定

_MEDIA_EXT = re.compile(r"\.(m3u8|mp4|m4s)(\?|$)", re.I)

# 小鹅通视频走腾讯云点播 / 自有 CDN，常见承载域名
_XIAOE_MEDIA_HOST = re.compile(
    r"(xiaoeknow\.com|xiaoe-tech\.com|xet\.tech|xeknow\.com|myqcloud\.com|qcloudcdn|qcloud\.com|vod[0-9a-z\-]*\.)",
    re.I,
)

def _is_douyin_media(u: str) -> bool:
    return "douyinvod.com" in u and ("mime_type=video_mp4" in u or u.endswith(".mp4"))

def _is_xiaoe_media(u: str) -> bool:
    p = urlparse(u)
    path = p.path or ""
    if not _MEDIA_EXT.search(path):
        return False
    # .ts 分片不要；m3u8 一律收（含商家自有 CDN），mp4 只收已知媒体域名，避免收到页面里的小素材
    if path.lower().rstrip("/").endswith(".m3u8") or ".m3u8" in path.lower():
        return True
    return bool(_XIAOE_MEDIA_HOST.search(p.netloc or ""))

def _media_score(u: str) -> int:
    """m3u8 优先于 mp4；master/主清单优先于码率子清单。"""
    low = u.lower()
    if ".m3u8" in low:
        if "playlist_eof" in low:      # 直播回放的完整清单
            return 25
        # 形如 xxx.f230.m3u8 / v.f421220.m3u8 是单码率子清单，主清单优先
        return 15 if re.search(r"\.f\d+\.m3u8", low) else 20
    return 5

# ---------------------------------------------------------------- cookie 导出

async def _dump_cookies(ctx, platform: str) -> Optional[Path]:
    """
    把 Playwright context 里的 cookie 导出成 Netscape 格式，供 yt-dlp 复用登录态。
    """
    try:
        cookies = await ctx.cookies()
    except Exception:
        return None
    if not cookies:
        return None

    lines = ["# Netscape HTTP Cookie File", "# generated by videoDownload", ""]
    fallback_exp = int(time.time()) + 7 * 86400
    for c in cookies:
        domain = c.get("domain") or ""
        if not domain:
            continue
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        secure = "TRUE" if c.get("secure") else "FALSE"
        try:
            expires = int(c.get("expires") or 0)
        except Exception:
            expires = 0
        if expires <= 0:
            expires = fallback_exp
        name = (c.get("name") or "").replace("\t", "").replace("\n", "")
        value = (c.get("value") or "").replace("\t", "").replace("\n", "")
        if not name:
            continue
        lines.append("\t".join([
            domain, include_sub, c.get("path") or "/", secure,
            str(expires), name, value,
        ]))

    path = cookie_file_for(platform)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path

# ---------------------------------------------------------------- 浏览器上下文

def _profile_dir(platform: str) -> Path:
    d = PROFILES / platform
    d.mkdir(parents=True, exist_ok=True)
    return d

_LAUNCH_ARGS = [
    "--autoplay-policy=no-user-gesture-required",
    "--disable-blink-features=AutomationControlled",
]

async def _new_persistent_ctx(p, platform: str, headless: bool):
    """需要登录态的平台：用持久化 profile，登录一次长期复用。"""
    return await p.chromium.launch_persistent_context(
        user_data_dir=str(_profile_dir(platform)),
        headless=headless,
        user_agent=UA,
        viewport={"width": 1440, "height": 900},
        args=_LAUNCH_ARGS,
    )

# ---------------------------------------------------------------- 抖音（原逻辑）

async def _sniff_douyin(url: str, headless: bool, wait_ms: int) -> Tuple[str, Optional[str], str]:
    hit_mp4 = None
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=headless)
        ctx = await browser.new_context()
        page = await ctx.new_page()

        def on_request(req):
            nonlocal hit_mp4
            if _is_douyin_media(req.url) and not hit_mp4:
                hit_mp4 = req.url

        page.on("request", on_request)

        try:
            await page.goto(url, wait_until="domcontentloaded")
            await page.wait_for_timeout(wait_ms)
        except Exception as e:
            await browser.close()
            return url, None, f"❌ 加载失败: {e}"

        await browser.close()
    return url, hit_mp4, ("✅ 解析成功" if hit_mp4 else "❌ 未捕获到直链")

# ---------------------------------------------------------------- 小鹅通

# 直播回放：详情页上要先点「进入回看」才会打开真正的播放页（而且是新标签页）
_ENTER_REPLAY_TEXTS = ("进入回看", "观看回放", "进入直播间", "立即观看", "查看回放")


async def _enter_replay(page, ctx):
    """
    在直播详情页上点「进入回看」。点击通常会开新标签页，
    返回真正承载播放器的那个 page；没有这类按钮就原样返回。
    """
    for text in _ENTER_REPLAY_TEXTS:
        try:
            loc = page.get_by_text(text, exact=False).first
            if not await loc.count():
                continue
            before = set(ctx.pages)
            await loc.click(timeout=5000)
            await page.wait_for_timeout(3000)
            fresh = [p for p in ctx.pages if p not in before]
            if fresh:
                target = fresh[-1]
                try:
                    await target.wait_for_load_state("domcontentloaded", timeout=30000)
                except Exception:
                    pass
                await target.wait_for_timeout(2000)
                return target
            return page
        except Exception:
            continue
    return page


_PLAY_SELECTORS = [
    ".xet-video-play",
    ".vjs-big-play-button",
    ".xplayer-play-btn",
    ".player-play-btn",
    "button[aria-label='播放']",
    ".video-play-btn",
    ".prism-big-play-btn",
]

async def _try_start_play(page) -> None:
    """小鹅通播放器不一定自动起播：先点常见播放按钮，再直接对 video 元素调 play()。"""
    for sel in _PLAY_SELECTORS:
        try:
            loc = page.locator(sel).first
            if await loc.count() and await loc.is_visible():
                await loc.click(timeout=1500)
                return
        except Exception:
            continue
    try:
        await page.evaluate(
            """() => {
                const vs = Array.from(document.querySelectorAll('video'));
                vs.forEach(v => { try { v.muted = true; v.play(); } catch (e) {} });
            }"""
        )
    except Exception:
        pass

def _login_wall(current_url: str, body_text: str, logged_in: bool = False) -> Optional[str]:
    u = (current_url or "").lower()
    if "no_permission" in u:
        if logged_in:
            return ("❌ 已登录，但服务端判定该账号对这节课**没有观看权限**。"
                    "常见原因：① 课程还没「购买/领取」；② PC 端登录的账号和"
                    "手机/小程序端买课的账号不是同一个；③ 该课程需按顺序解锁。"
                    "请先在浏览器里确认这一节能正常播放，再回来解析。")
        return "❌ 无观看权限：未检测到登录态，或该账号未购买/未领取此课程"
    if "/login" in u or "pc_account" in u:
        return "❌ 未登录：请先点『打开浏览器登录』完成登录后重试"
    t = body_text or ""
    if "您还未购买" in t or "暂无法学习" in t:
        return "❌ 无观看权限：该账号未购买/未领取此课程"
    if "登录" in t and "扫码" in t:
        return "❌ 未登录：请先点『打开浏览器登录』完成登录后重试"
    return None

async def _capture_title(resp, store: dict) -> None:
    """
    顺带记下这节课的真实名字（用于文件命名）。拿不到就退回用资源 id 命名，
    所以这里是纯锦上添花，不作为下载的前置条件。
    """
    try:
        if "video.detail_info" not in resp.url and "video.detail" not in resp.url:
            return
        data = (await resp.json()).get("data") or {}
        info = data.get("video_info") or {}
        for key in ("file_name", "title", "resource_name"):
            v = info.get(key) or data.get(key)
            if v:
                store["title"] = str(v)
                return
    except Exception:
        pass


async def _attempt(page, target: str, wait_ms: int,
                   hits: List[str], logged_in: bool, ctx=None) -> Optional[str]:
    """打开一个入口并尝试起播。返回 None 表示正常（可能已抓到直链），否则返回拦截原因。"""
    await page.goto(target, wait_until="domcontentloaded", timeout=60000)
    await page.wait_for_timeout(3000)

    body_text = ""
    try:
        body_text = await page.inner_text("body", timeout=3000)
    except Exception:
        pass
    wall = _login_wall(page.url, body_text, logged_in)
    if wall:
        return wall

    # 直播回放要先点「进入回看」，之后播放器在新标签页里
    if ctx is not None:
        page = await _enter_replay(page, ctx)

    await _try_start_play(page)

    deadline = time.monotonic() + (int(wait_ms) + XIAOE_EXTRA_WAIT_MS) / 1000.0
    replayed = False
    while time.monotonic() < deadline and not hits:
        await page.wait_for_timeout(500)
        if not replayed and time.monotonic() > deadline - (XIAOE_EXTRA_WAIT_MS / 1000.0):
            await _try_start_play(page)
            replayed = True

    if not hits:
        try:
            return _login_wall(page.url, await page.inner_text("body", timeout=2000), logged_in)
        except Exception:
            return _login_wall(page.url, "", logged_in)
    return None


async def _sniff_xiaoe_in_ctx(ctx, url: str, wait_ms: int,
                              logged_in: bool) -> Tuple[Optional[str], Optional[str], str]:
    """
    在一个已经建好、已注入登录态的 context 里嗅探一条链接。
    返回 (直链, 课程标题, 状态说明)。单次模式和并发模式共用这段。
    """
    hits: List[str] = []
    meta: dict = {}

    # 优先走 middle_page 入口：原始链接里的 product_id 可能不是你买的那个商品，
    # 会被服务端判成 no_permission。两个入口都试，谁先出直链算谁的。
    targets: List[str] = []
    norm = normalize_xiaoe_url(url)
    if norm and norm != url:
        targets.append(norm)
    targets.append(url)

    def on_request(req):
        u = req.url
        if _is_xiaoe_media(u) and u not in hits:
            hits.append(u)

    ctx.on("request", on_request)
    ctx.on("response", lambda r: asyncio.create_task(_capture_title(r, meta)))

    page = await ctx.new_page()
    walls: List[str] = []
    try:
        for target in targets:
            wall = await _attempt(page, target, wait_ms, hits, logged_in, ctx)
            if hits:
                break
            if wall:
                walls.append(wall)
    except Exception as e:
        return None, meta.get("title"), f"❌ 加载失败: {e}"
    finally:
        try:
            await page.close()
        except Exception:
            pass

    title = meta.get("title")
    if hits:
        best = sorted(hits, key=_media_score, reverse=True)[0]
        kind = "m3u8" if ".m3u8" in best.lower() else "mp4"
        return best, title, f"✅ 解析成功（{kind}）" + (f" · {title}" if title else "")
    if walls:
        return None, title, walls[0]
    return None, title, "❌ 未捕获到直链（可尝试关掉无头模式、调大等待时长，或确认账号已购买该课程）"


async def _sniff_xiaoe(url: str, headless: bool, wait_ms: int,
                       cookie_mode: str = COOKIE_SOURCE) -> Tuple[str, Optional[str], str]:
    async with async_playwright() as p:
        try:
            ctx = await _new_persistent_ctx(p, "xiaoe", headless)
        except Exception as e:
            return url, None, f"❌ 浏览器启动失败（登录窗口是否还开着？同一 profile 不能同时打开两次）: {e}"

        logged_in = False
        try:
            injected, _note = cookie_source.prepare("xiaoe", cookie_mode)
            if injected:
                await ctx.add_cookies(injected)
                logged_in = cookie_source.looks_logged_in(injected)
        except Exception as e:
            await ctx.close()
            return url, None, f"❌ 注入登录态失败: {e}"

        try:
            direct, title, status = await _sniff_xiaoe_in_ctx(ctx, url, wait_ms, logged_in)
            if title:
                TITLES[url] = title
            await _dump_cookies(ctx, "xiaoe")
        finally:
            try:
                await ctx.close()
            except Exception:
                pass
    return url, direct, status


# ---------------------------------------------------------------- 并发嗅探

class SharedSniffer:
    """
    共享一个浏览器进程、每条任务开独立 context，因此可以并发。

    不能用持久化 profile：同一个 user_data_dir 不允许被并发打开。
    登录态改为每个 context 单独注入 cookie，效果一样。
    """

    def __init__(self, browser, cookies: List[dict], logged_in: bool):
        self._browser = browser
        self._cookies = cookies
        self.logged_in = logged_in

    async def sniff(self, url: str, wait_ms: int) -> Tuple[Optional[str], Optional[str], str]:
        ctx = await self._browser.new_context(
            user_agent=UA, viewport={"width": 1440, "height": 900})
        try:
            if self._cookies:
                await ctx.add_cookies(self._cookies)
            direct, title, status = await _sniff_xiaoe_in_ctx(ctx, url, wait_ms, self.logged_in)
            if title:
                TITLES[url] = title
            return direct, title, status
        finally:
            try:
                await ctx.close()
            except Exception:
                pass


@asynccontextmanager
async def shared_sniffer(headless: bool = True, cookie_mode: str = COOKIE_SOURCE):
    """并发嗅探用：一个浏览器进程 + 一份登录态，交给多个任务共享。"""
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=headless, args=_LAUNCH_ARGS)
        cookies, note = cookie_source.prepare("xiaoe", cookie_mode)
        logged_in = cookie_source.looks_logged_in(cookies) if cookies else False
        try:
            yield SharedSniffer(browser, cookies, logged_in), note
        finally:
            try:
                await browser.close()
            except Exception:
                pass


# ---------------------------------------------------------------- 对外入口

async def sniff_one(url: str, headless: bool, wait_ms: int,
                    cookie_mode: str = COOKIE_SOURCE) -> Tuple[str, Optional[str], str]:
    pf = detect_platform_loose(url)
    if pf == "xiaoe":
        return await _sniff_xiaoe(url, headless, wait_ms, cookie_mode)
    if pf == "douyin":
        return await _sniff_douyin(url, headless, wait_ms)
    return url, None, "❌ 不支持的平台（目前支持：抖音、小鹅通）"

async def sniff_serial(urls: List[str], headless: bool, wait_ms: int,
                       cookie_mode: str = COOKIE_SOURCE):
    results = []
    for u in urls:
        results.append(await sniff_one(u, headless, wait_ms, cookie_mode))
    return results

# ---------------------------------------------------------------- 登录

async def open_login_async(url: str, timeout_ms: int = LOGIN_WAIT_MS) -> str:
    """
    打开有头持久化浏览器让用户手动登录（扫码/账号密码都行）。
    登录完成后关闭窗口即可，会话保存在 .browser_profiles/<平台>/，后续解析自动复用。
    """
    pf = detect_platform_loose(url) or "xiaoe"
    async with async_playwright() as p:
        try:
            ctx = await _new_persistent_ctx(p, pf, headless=False)
        except Exception as e:
            return f"❌ 浏览器启动失败（是否已有一个登录窗口开着？）: {e}"

        page = ctx.pages[0] if ctx.pages else await ctx.new_page()
        try:
            await page.goto(url, wait_until="domcontentloaded", timeout=60000)
        except Exception:
            pass

        deadline = time.monotonic() + timeout_ms / 1000.0
        saved = False
        while time.monotonic() < deadline:
            await asyncio.sleep(2)
            try:
                if not ctx.pages:  # 用户关掉了窗口
                    break
                if await _dump_cookies(ctx, pf):
                    saved = True
            except Exception:
                break  # context 已关闭

        try:
            await ctx.close()
        except Exception:
            pass

    if saved:
        return f"✅ 登录态已保存（{pf}）。现在回到上面点『一键解析』即可，无头模式可以保持勾选。"
    return "⚠️ 未捕获到登录态：请确认在弹出的窗口里完成了登录，再关闭窗口。"

def open_login(url: str, timeout_ms: int = LOGIN_WAIT_MS) -> str:
    return asyncio.run(open_login_async(url, timeout_ms))
